#!/usr/bin/env python3
import json
import hashlib
import sys
import math
import random
import coloredlogs
import logging
from typing import List, Dict

g_logger = None


class SimulatorParameters:
    # Parameters in the configuration file (will be read from the file during initialization)
    def __init__(self) -> None:
        self.total_nodes = 0
        self.number_of_slow_nodes = 0
        self.number_of_fast_nodes = 0
        self.txn_interarrival_mean = 0
        self.nodes_list: List = []

    # Initialize the simulator parameters
    def initial_setup(self, config_file_name: str):
        global g_logger
        g_logger.debug(f"{config_file_name=}")

        # Open the config file and parse it
        config_file = open(config_file_name)
        parameters = json.load(config_file)

        # Read parameters from the config file

        # Total nodes present in the P2P cryptocurrency network
        self.total_nodes = parameters["total-nodes"]

        # parameters["slow-nodes"] === z%
        self.number_of_slow_nodes = (parameters["slow-nodes-percent"] * self.total_nodes) // 100

        if (self.number_of_slow_nodes > self.total_nodes):
            g_logger.error('Condition not satisfied: 0 <= slow-nodes-percent <= 100')
            g_logger.warning('Making all nodes as slow because "slow-nodes-percent > 100"')
            self.number_of_slow_nodes = self.total_nodes

        # (100 - z)% nodes are fast nodes
        self.number_of_fast_nodes = self.total_nodes - self.number_of_slow_nodes

        # Exponential distribution mean for the interarrival between transactions generated by a peer
        self.txn_interarrival_mean = parameters["txn-interarrival-mean"]

    # Print all the Simulator Parameters to "stdout"
    def log_parameters(self):
        print(f"Number of peers specified in the config file : {self.total_nodes}")
        print(f"Number of slow nodes : {self.number_of_slow_nodes}")
        print(f"Number of fast nodes : {self.number_of_fast_nodes}")
        print(f"Transaction Interarrival Mean = {self.txn_interarrival_mean}")
        print(f"Nodes List = {self.nodes_list}")


# Structure of a node on the P2P network
class Node:
    def __init__(self, sp: SimulatorParameters):
        # List of connected peers
        self.neighbors = []
        self.txn_interarrival_time = (-1.0 / sp.txn_interarrival_mean) * math.log(random.uniform(0.1, 1))

    # Adding new peer to the neighbors list
    # (inserts an edge between this and new_peer in the node graph)
    def add_new_peer(self, new_peer):
        self.neighbors.append(new_peer)


class Transaction:
    def __init__(self, sender, receiver, amount):
        self.sender = sender
        self.receiver = receiver
        self.amount = amount


class EventQueue:
    def __init__(self):
        self.events = []


def Main(args: Dict):
    ss = SimulatorParameters()
    ss.initial_setup(args['config'])
    ss.log_parameters()


if __name__ == '__main__':
    import argparse

    my_parser = argparse.ArgumentParser(prog='simulator.py',
                                        description='Discrete Event Simulator for a P2P Cryptocurrency Network',
                                        epilog='Enjoy the program :)',
                                        prefix_chars='-',
                                        allow_abbrev=False,
                                        add_help=True)
    my_parser.version = '1.0'
    my_parser.add_argument('--version', action='version')
    my_parser.add_argument('-D',
                           '--debug',
                           action='store_true',
                           help='Print debug information')
    my_parser.add_argument('-c',
                           '--config',
                           action='store',
                           type=str,
                           help='Path to the config file',
                           required=True)

    # Execute the parse_args() method
    args: argparse.Namespace = my_parser.parse_args()

    # Initialize "g_logger"
    g_logger = logging.getLogger(__name__)
    # REFER: https://stackoverflow.com/questions/384076/how-can-i-color-python-logging-output
    #            - https://github.com/xolox/python-coloredlogs
    if args.debug:
        # g_logger.setLevel(logging.DEBUG)
        coloredlogs.install(fmt='%(levelname)-8s :: [%(lineno)4s] %(name)10s :: %(message)s', level='DEBUG',
                            logger=g_logger)
    else:
        # g_logger.setLevel(logging.INFO)
        coloredlogs.install(fmt='%(levelname)-8s :: [%(lineno)4s] %(name)10s :: %(message)s', level='INFO',
                            logger=g_logger)

    g_logger.debug("Debugging is ON")
    g_logger.debug(f"{args=}")
    g_logger.handlers[
        0].flush()  # REFER: https://stackoverflow.com/questions/13176173/python-how-to-flush-the-log-django/13753911

    Main(vars(args))
